#!/usr/bin/env bash

# configures a brand new Ubuntu machine to the requirements asked in this task
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script as root or with sudo."
    exit 1
fi

apt update
apt install -y haproxy

cat <<EOL > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend myapp
    bind *:80
    default_backend myapp-backend

backend myapp-backend
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOL

systemctl enable haproxy
systemctl restart haproxy

systemctl status haproxy

echo "HAProxy is now installed and configured."
