#!/usr/bin/env bash
# A Bash script that generates a MySQL dump and creates a compressed archive out of it.
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
format="$day-$month-$year.tar.gz"
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czvf "$format" backup.sql
