#!/usr/bin/env bash
# Configures nginx to run, and listen on port 80 of all the server’s active IPv4 IPs
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kil -9 "$(cat /var/run/run/nginx.pid)"
