#!/usr/bin/env bash
# A Bash script that loops from 1 to 10

count=1
while [[ $count -le 10 ]];
do
    echo "Best School"
    count=$(( count + 1))
    if [ $count -eq 4 ]
    then
        echo "bad luck"
        count=$(( count + 1))
    elif [ $count -eq 8 ]
    then
        echo "good luck"
        count=$(( count + 1 ))
    fi
done
