#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server

# Update /etc/hosts to configure localhost
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null

# Configure DNS resolution for facebook.com
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
