#!/usr/bin/env bash
# A  Bash script that displays all active IPv4 IPs on the machine it’s executed on

ip_addresses=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*')

for ip in $ip_addresses; do
    echo "$ip"
done
