#!/usr/bin/env bash
# A Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.

server="54.174.66.106"
private_key="~/.ssh/school"

ssh -i "$private_key" ubuntu@"$server"

